export const MainData = [
  {
    id: 1,
    items: [
      {
        card: 1,
        tittle: ".COM",
        price: "$5.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 2,
        tittle: ".AI",
        price: "$55.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 3,
        tittle: ".NET",
        price: "$7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 4,
        tittle: ".HEALTH",
        price: "7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 5,
        tittle: ".CO.UK",
        price: "$3.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 6,
        tittle: ".ORG",
        price: "$15.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 7,
        tittle: ".CO",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 8,
        tittle: ".SEA",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
    ],
  },
  {
    id: 2,
    items: [
      {
        card: 3,
        tittle: ".NET",
        price: "$7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 4,
        tittle: ".HEALTH",
        price: "7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 5,
        tittle: ".CO.UK",
        price: "$3.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 6,
        tittle: ".ORG",
        price: "$15.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 7,
        tittle: ".CO",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 1,
        tittle: ".COM",
        price: "$5.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 2,
        tittle: ".AI",
        price: "$55.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 8,
        tittle: ".SEA",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
    ],
  },
  {
    id: 3,
    items: [
      {
        card: 1,
        tittle: ".COM",
        price: "$5.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 2,
        tittle: ".AI",
        price: "$55.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 3,
        tittle: ".NET",
        price: "$7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 4,
        tittle: ".HEALTH",
        price: "7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 5,
        tittle: ".CO.UK",
        price: "$3.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 6,
        tittle: ".ORG",
        price: "$15.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 7,
        tittle: ".CO",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 8,
        tittle: ".SEA",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
    ],
  },
  {
    id: 4,
    items: [
      {
        card: 3,
        tittle: ".NET",
        price: "$7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 4,
        tittle: ".HEALTH",
        price: "7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 5,
        tittle: ".CO.UK",
        price: "$3.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 6,
        tittle: ".ORG",
        price: "$15.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 7,
        tittle: ".CO",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 1,
        tittle: ".COM",
        price: "$5.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 2,
        tittle: ".AI",
        price: "$55.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 8,
        tittle: ".SEA",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
    ],
  },
  {
    id: 5,
    items: [
      {
        card: 1,
        tittle: ".COM",
        price: "$5.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 2,
        tittle: ".AI",
        price: "$55.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 3,
        tittle: ".NET",
        price: "$7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 4,
        tittle: ".HEALTH",
        price: "7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 5,
        tittle: ".CO.UK",
        price: "$3.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 6,
        tittle: ".ORG",
        price: "$15.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 7,
        tittle: ".CO",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 8,
        tittle: ".SEA",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
    ],
  },
  {
    id: 6,
    items: [
      {
        card: 3,
        tittle: ".NET",
        price: "$7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 4,
        tittle: ".HEALTH",
        price: "7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 5,
        tittle: ".CO.UK",
        price: "$3.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 6,
        tittle: ".ORG",
        price: "$15.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 7,
        tittle: ".CO",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 1,
        tittle: ".COM",
        price: "$5.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 2,
        tittle: ".AI",
        price: "$55.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 8,
        tittle: ".SEA",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
    ],
  },
  {
    id: 7,
    items: [
      {
        card: 1,
        tittle: ".COM",
        price: "$5.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 2,
        tittle: ".AI",
        price: "$55.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 3,
        tittle: ".NET",
        price: "$7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 4,
        tittle: ".HEALTH",
        price: "7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 5,
        tittle: ".CO.UK",
        price: "$3.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 6,
        tittle: ".ORG",
        price: "$15.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 7,
        tittle: ".CO",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 8,
        tittle: ".SEA",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
    ],
  },
  {
    id: 8,
    items: [
      {
        card: 3,
        tittle: ".NET",
        price: "$7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 4,
        tittle: ".HEALTH",
        price: "7.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 5,
        tittle: ".CO.UK",
        price: "$3.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 6,
        tittle: ".ORG",
        price: "$15.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 7,
        tittle: ".CO",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 1,
        tittle: ".COM",
        price: "$5.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 2,
        tittle: ".AI",
        price: "$55.99/yr",
        description: "Instead of $10.99/yr",
      },
      {
        card: 8,
        tittle: ".SEA",
        price: "$26.33/yr",
        description: "Instead of $10.99/yr",
      },
    ],
  },
];
